name: AI Code Review with OpenAI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  ai_code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit
      - name: AI Code Review
        uses: AleksandrFurmenkovOfficial/ai-code-review@1d75404db7d56026c81700b5b8e5e8c613234e69
        with:
          token: ${{ secrets.TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          ai_provider: 'openai'
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          openai_model: 'gpt-4o'